config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles
resources :article_categories
resources :categories
resources :comments
resources :users

    root to: "articles#index"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  # Page de recherche
  get '/search', to: 'articles#search'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete  'logout', to: 'sessions#destroy'

  resources :categories
  resources :comments, except: [:index, :show, :destroy, :edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_save{ self.email = email.downcase }

  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 15}
  validates :email, presence: true, uniqueness: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
                                                               message: "Not a valid email format" }
  has_secure_password

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Alpha Blog"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:success] = "Succesfully updated your account"
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def show
    @articles = @user.articles
  end

  def destroy
    @user.destroy
    flash[:danger] = "Your account has been deleted"
    redirect_to users_path
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :bio)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You need to be logged in to do this"
      redirect_to login_path
    end
  end

end

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

  <div class="row">
    <div class="col-xs-12">

      <%= form_for(@user, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>

        <div class="form-group">
          <div class="control-label col-sm-2 col-sm-offset-1">
            <%= f.label :username %>
          </div>
          <div class="col-sm-6">
            <%= f.text_field :username, class: 'form-control clearfix', placeholder: "Username", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2 col-sm-offset-1">
            <%= f.label :email %>
          </div>
          <div class="col-sm-6">
            <%= f.email_field :email, class: 'form-control clearfix', placeholder: "Email" %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2  col-sm-offset-1">
            <%= f.label :password %>
          </div>
          <div class="col-sm-6">
            <%= f.password_field :password, class: 'form-control clearfix', placeholder: 'Password' %>
          </div>
        </div>
        <% if !@user.new_record? %>
          <div class="form-group">
            <div class="control-label col-sm-offset-2 col-sm-1">
              <%= f.label :bio %>
            </div>
            <div class="col-sm-6">
              <%= f.text_area :bio, rows: 5, class: 'form-control clearfix', placeholder: 'Bio' %>
            </div>
          </div>
          <% end %>
            <div class="form-group">
              <div class="col-sm-offset-3 col-sm-10 ">
                <%= f.submit(@user.new_record? ? "Inscription" : "Update Compte", class: 'btn btn-primary') %>
                  <%= link_to "Annuler", articles_path, class: 'btn btn-default' %>
              </div>
            </div>

            <% end %>

    </div>
  </div>

app/views/users/edit.html.erb
<section class="jumbotron text-center">
  <h1>Editer votre compte!</h1>
  <h3>Vous pouvez régler vos informations ici</h3>
</section>

<section class="container-fluid">

  <%= render 'form'%>

</section>

app/views/users/index.html.erb
<section class="jumbotron text-center">
  <h1>Liste des utilisateurs</h1>
  <br />
  <h3>
    <%= link_to 'Créer un nouvel utilisateur', signup_path, class: 'btn btn-lg btn-success' %>
  </h3>
</section>

<section class="container-fluid">

  <div class="col-sm-6 col-sm-offset-3 text-center">
  </div>

  <% @users.each do |user| %>

    <article class="container article col-md-8 col-md-offset-2 text-center">
      <div class="row">
        <div class="col-md-12 article-title text-center">
          <h2>
            <%= link_to user.username, user_path(user) %>
          </h2>
          <p>
            <%= pluralize(user.articles.count, "articles") %>
          </p>
          <% if logged_in? && current_user.admin? %>
            <%= link_to 'Delete User', user_path(user), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger'%>
              <% end %>
        </div>
      </div>
    </article>

    <% end %>

      <div class="col-sm-6 col-sm-offset-3 text-center">
      </div>

</section>

app/views/users/new.html.erb
<section class="jumbotron text-center">
  <h1>Inscrivez vous dès maintenant !</h1>
  <h3>Créer un compte et partagez vos idées</h3>
</section>

<section class="container-fluid">

  <%= render 'form'%>
</section>

app/views/users/show.html.erb
<section class="jumbotron text-center">
  <%= gravatar_for @user, size: 100, classes: 'img-circle' %>
    <h1>
      <%= @user.username %>
    </h1>
    <br />
    <br />
    <% if logged_in? && (@user == current_user || current_user.admin?) %>
      <p>
        <%= link_to 'Editer Compte', edit_user_path(@user), class: 'btn btn-primary' %> |
          <%= link_to 'Supprimer Compte', user_path(@user), method: :delete, data: {confirm: "Etes vous sur?"}, class: 'btn btn-danger' %>
      </p>
      <br />
      <% end %>
</section>

<section class="container-fluid">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <p id="bio">
        <%= @user.bio %>
      </p>
    </div>
  </div>

  <h2 class="col-sm-10 col-sm-offset-1 text-center" id="user-article-heading">Articles</h2>

  <%= render 'shared/article', obj: @user_articles %>

    <div class="row col-md-8 col-md-offset-2 text-center" style="margin-top: 3em;">
      <p>
        <%= link_to 'Ecrire un article', new_article_path, class: 'btn btn-success btn-lg' %>
      </p>
    </div>

    <div class="col-sm-6 col-sm-offset-3 text-center">
    </div>

</section>