config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles
resources :article_categories
resources :categories
resources :comments
resources :users

    root to: "articles#index"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  # Page de recherche
  get '/search', to: 'articles#search'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete  'logout', to: 'sessions#destroy'

  resources :categories
  resources :comments, except: [:index, :show, :destroy, :edit, :update]

end

app/views/shared/_article.html.erb
<% if @articles.each do |article| %>
  <article class="container article col-md-8 col-md-offset-2 text-center">
    <img src="<%= article.image %>">
    <h2>
      <%= link_to article.title, article_path(article) %>
    </h2>
    <small>
      <i>
        <%= article.created_at.strftime("%B %d, %Y") %>
      </i>
      <br />
      <b>
        <%= link_to(article.user.username, user_path(article.user)) if article.user %>
      </b>
    </small>
    <br />
    <br />
    <p>
      <%= simple_format(truncate(article.description, length: 500)) %>
    </p>
    <br />
    <% if article.categories.any? %>
      <p>
        <%= render article.categories %>
      </p>
      <br />
      <% end %>
        <% if logged_in? && (article.user == current_user || current_user.admin?)  %>
          <p>
            <%= link_to 'Editer', edit_article_path(article), class: 'btn btn-default' %>
              <%= link_to 'Annuler', article_path(article), method: :delete, data: {confirm: "Etes vous sur ?"}, class: 'btn btn-danger' %>
          </p>
          <% end %>
  </article>
  <% end.empty? %>

    <div class="text-center">Aucun contenu !</div>
    <% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title" style="text-transform: uppercase">
        <b>Your article has the following errors:</b>
      </h3>
      <div class="panel-body">
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
            <% end %>
        </ul>
      </div>
    </div>
  </div>

  <% end %>