config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles
resources :article_categories
resources :categories
resources :comments
resources :users

    root to: "articles#index"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  # Page de recherche
  get '/search', to: 'articles#search'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete  'logout', to: 'sessions#destroy'

  resources :categories
  resources :comments, except: [:index, :show, :destroy, :edit, :update]

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name

end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Category.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Category.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, except: [:create, :new, :index]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "Category was created succesfully"
      redirect_to categories_path
    else
      render :new
    end

  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category was succesfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @articles = @category.articles
  end

  def destroy
    @category.destroy
    flash[:danger] = "Category deleted"
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/views/categories/_category.html.erb
<span class="badge category_name"><%= link_to category.name, category_path(category), style: 'color: white' %></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

  <div class="row">
    <div class="col-xs-12">

      <%= form_for(@category, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>

        <div class="form-group">
          <div class="control-label col-sm-2 col-sm-offset-1">
            <%= f.label :name %>
          </div>
          <div class="col-sm-6">
            <%= f.text_field :name, class: 'form-control clearfix', placeholder: "Nouvelle catégorie", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2 col-sm-offset-1">
            <%= f.label :description %>
          </div>
          <div class="col-sm-6">
            <%= f.text_area :description, class: 'form-control clearfix', placeholder: "Description", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-10">
            <%= f.submit class: 'btn btn-primary'%>
              <%= link_to "Annuler", articles_path, class: 'btn btn-default' %>
                <% if show_delete %>
                  <%= link_to "Supprimer", category_path(@category), method: :delete, data: {confirm: "Etes vous sur ?"}, class: 'btn btn-danger' %>
                    <% end %>
          </div>
        </div>

        <% end %>

    </div>
  </div>

app/views/categories/edit.html.erb
<section class="jumbotron text-center">
  <h1>Editer la Categorie:
    <i>
      <%= @category.name %>
    </i>
  </h1>
</section>

<section class="container-fluid">

  <%= render 'form', show_delete: true %>

</section>

app/views/categories/index.html.erb
<section class="jumbotron text-center">
  <h1>Catégories</h1>
  <% if logged_in? %>
    <h3>
      <%= link_to 'Créer une nouvelle categorie', new_category_path, class: 'btn btn-lg btn-success' %>
    </h3>
    <% end %>
</section>

<section class="container-fluid">


  <% @categories.each do |category| %>

    <article class="container article col-md-8 col-md-offset-2 text-center">
      <h2>
        <%= link_to category.name, category_path(category) %>
      </h2>
      <br />
      <smal>
        <%= pluralize(category.articles.count, "article") %>
      </smal>
    </article>

    <% end %>



</section>

app/views/categories/new.html.erb
<section class="jumbotron text-center">
  <h1>Créez une catégorie!</h1>
  <h3>Choisissez une catégorie pour vos prochains articles</h3>
</section>

<section class="container-fluid">

  <%= render 'form', show_delete: false %>

</section>

app/views/categories/show.html.erb
<section class="jumbotron text-center">
  <h1>Tous les articles dans
    <%= @category.name %>
  </h1>
  <br />
  <% if logged_in? && current_user.admin? %>
    <%= link_to 'Editer Categorie', edit_category_path(@category), class: 'btn btn-primary' %>
      <%= link_to 'Supprimer Categorie', category_path(@category), method: :delete, data: {confirm: "Etes vous sur ?"}, class: 'btn btn-danger' %>
        <% end %>

</section>

<section class="container-fluid">

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <p id="bio">
        <%= @category.description %>
      </p>
    </div>
  </div>

  <h2 class="col-sm-10 col-sm-offset-1 text-center" id="user-article-heading">Articles</h2>

  <%= render 'shared/article', obj: @category_articles %>
    <div class="row col-md-12" style="margin-bottom: 3em;">
      <p class="text-center">
        <%= link_to '< Toutes les catégories', categories_path, class: 'btn btn-default' %>
      </p>
    </div>

</section>