config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles
resources :article_categories
resources :categories
resources :comments
resources :users

    root to: "articles#index"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  # Page de recherche
  get '/search', to: 'articles#search'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete  'logout', to: 'sessions#destroy'

  resources :categories
  resources :comments, except: [:index, :show, :destroy, :edit, :update]

end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}" %>'>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>

app/views/layouts/_navigation_bar.html.erb
<header id="header">
  <nav class="navbar navbar-default navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
          aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'EEMI Blog', root_path, class: 'navbar-brand active' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <!--<li class="active"><a href="#">About<span class="sr-only">(current)</span></a></li>-->
          <li>
            <%= link_to 'A propos', about_path %>
          </li>
          <li>
            <%= link_to 'Articles', articles_path %>
          </li>
          <li>
            <%= link_to 'Users', users_path %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Catégories
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Toutes les catégories', categories_path %>
              </li>
              <% Category.all.each do |cat| %>
                <li>
                  <%= link_to cat.name, category_path(cat) %>
                </li>
                <% end %>
                  <% if logged_in? && current_user.admin? %>
                    <li class="divider" role="separator"></li>
                    <li>
                      <%= link_to "Créer une nouvelle catégorie", new_category_path %>
                    </li>
                    <% end %>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Votre Profil
                <%= "Admin" if current_user.admin? %>
                  <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Votre Profil', user_path(current_user) %>
                </li>
                <li>
                  <%= link_to 'Editer votre Profil', edit_user_path(current_user) %>
                </li>
                <li>
                  <%= link_to "Se déconnecter", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
            <% else %>
              <li>
                <%= link_to "Connexion", login_path %>
              </li>
              <li>
                <%= link_to 'Inscription', signup_path %>
              </li>
              <% end %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>EEMI Blog</title>
  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/navigation_bar' %>
    <%= render 'layouts/flash' %>

      <%= yield %>

        <!-- <%=  debug(params) if Rails.env.development? %> -->
        <script type="text/javascript">
          $(document).ready(function () {
            $('.dropdown-toggle').dropdown();
          });
        </script>
</body>

</html>